language: php

php:
  - 7.2
  - 7.3

env:
  global:
    - DEFAULT=1

matrix:
  fast_finish: true

  include:
    - php: 7.2
      env: PHPCS=1 DEFAULT=0

    - php: 7.2
      env: PHPSTAN=1 DEFAULT=0

before_script:
  - composer install --prefer-dist --no-interaction
  - if [[ $PHPCS = 1 ]]; then composer require cakephp/cakephp-codesniffer:dev-next; fi
  - if [[ $PHPSTAN = 1 ]]; then composer require phpstan/phpstan:^0.11; fi

script:
  - if [[ $DEFAULT = 1 ]]; then vendor/bin/phpunit; fi
  - if [[ $PHPCS = 1 ]]; then vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP src/; fi
  - if [[ $PHPSTAN = 1 ]]; then vendor/bin/phpstan analyse src; fi

notifications:
  email: false
